// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRrWk61e3ejJ8uDfmOATpc_nZDI1CcHeY',
    appId: '1:424768951438:web:36b97504ef80dacbcb65df',
    messagingSenderId: '424768951438',
    projectId: 'whisky-shop-point',
    authDomain: 'whisky-shop-point.firebaseapp.com',
    storageBucket: 'whisky-shop-point.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQIJWePC0ch1t5Zz7lK-KPy_f2uqdjMD4',
    appId: '1:424768951438:android:c172b8e79db35bb0cb65df',
    messagingSenderId: '424768951438',
    projectId: 'whisky-shop-point',
    storageBucket: 'whisky-shop-point.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4AuFAYV612vp62Q16Psl-_sgmaKRFwBs',
    appId: '1:424768951438:ios:715f16f41b1cb526cb65df',
    messagingSenderId: '424768951438',
    projectId: 'whisky-shop-point',
    storageBucket: 'whisky-shop-point.firebasestorage.app',
    iosBundleId: 'com.whiskyshop.whiskyshopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4AuFAYV612vp62Q16Psl-_sgmaKRFwBs',
    appId: '1:424768951438:ios:715f16f41b1cb526cb65df',
    messagingSenderId: '424768951438',
    projectId: 'whisky-shop-point',
    storageBucket: 'whisky-shop-point.firebasestorage.app',
    iosBundleId: 'com.whiskyshop.whiskyshopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRrWk61e3ejJ8uDfmOATpc_nZDI1CcHeY',
    appId: '1:424768951438:web:c5f64352b1dbba99cb65df',
    messagingSenderId: '424768951438',
    projectId: 'whisky-shop-point',
    authDomain: 'whisky-shop-point.firebaseapp.com',
    storageBucket: 'whisky-shop-point.firebasestorage.app',
  );
}
